### ISSUE TITLE
Support for Odroid Xu4

### ISSUE THREAD

**Issue by mhessler97** [adafruit/Adafruit_Blinka#188]
Would it be possible to add support for the Odroid Xu4. I want to use the BNO055 with my Odroid Xu4 but since there is no support for it for the odroid yet I need to update the library for it which is currently using the deprecated Adafruit Python GPIO Library. So any assistance with this would be appreciated.

**Comment by makermelissa** [comment]
Yes, that’s one that I have and was planning on adding in the near future.

**Comment by hhk7734** [comment]
Hi, @mhessler97, @makermelissa
I will check the Odroid-XU4 gpiod pin map soon.
But, due to the hardware characteristics of Odroid XU4, GPIO-related operations may not work well.

If you have time to test, use Arduino to make sure the sensor is working properly.
Ref: https://github.com/hhk7734/oduino

**Comment by hhk7734** [comment]
Blinka supports XU4 #294 :) :+1:

**Comment by makermelissa** [comment]
Thank you for adding it @hhk7734
