### ISSUE TITLE
Example Code on Code Page Not working ...

### ISSUE THREAD

**Issue by sealyons** [adafruit/Adafruit_Blinka#567]
I tried to run the Example code on the Code Page and I get a traceback saying the module 'testing' can't be found.  Is this code still supposed to be working?  I'm trying to run on a Raspberry Pi 400.

from testing import test_module_name
test_module_name("testing.universal.digitalio")

**Comment by dhalbert** [comment]
`testing` is the module in this directory: https://github.com/adafruit/Adafruit_Blinka/tree/main/test/src/testing

**Comment by sealyons** [comment]
Hi Dan,This really doesn't help me. My issue is I get a teaceback when I try to access the testing module from my Pi400. Everything else appears to be accessible. If the testing module exists in the latest release, why am I getting a traceback? Appreciate any additional guidance. Thanks, Chris Lyons 
-------- Original message --------From: Dan Halbert ***@***.***> Date: 3/18/22  11:10 PM  (GMT-05:00) To: adafruit/Adafruit_Blinka ***@***.***> Cc: sealyons ***@***.***>, Author ***@***.***> Subject: Re: [adafruit/Adafruit_Blinka] Example Code on Code Page Not working ... (Issue #567) 
testing is the module in this directory: https://github.com/adafruit/Adafruit_Blinka/tree/main/test/src/testing

**Comment by makermelissa** [comment]
First of all, the tests were originally written when Blinka only worked on MicroPython. I don't think testing has been used or updated in a long time (like 3-4 years). Since testing is because it is outside of the root src folder (https://github.com/adafruit/Adafruit_Blinka/tree/main/src), the way to run it is to first make sure you have cloned the Blinka repo. Then go into the test/src folder and run it. It should start running the test suite, but due to not being updated in years, it will likely fail.
