### ISSUE TITLE
not yet ready for public consumption

### ISSUE THREAD

**Issue by Dmole** [adafruit/Adafruit_Blinka#70]
https://github.com/adafruit/Adafruit_Blinka/blob/40f44f6bde990ffac815131743c0a390e84cb51a/src/adafruit_blinka/microcontroller/generic_linux/i2c.py#L1

https://github.com/adafruit/Adafruit_Python_PureIO/blob/master/README.md

Also it is not marked as a dependency for pip3.

**Comment by brennen** [comment]
we're not exactly the public in the sense intended by that README, since we author both libraries.  that said, i noticed this yesterday when [adding it to the dependencies](https://github.com/adafruit/Adafruit_Blinka/pull/68) (we'll do a new release to PyPI shortly), and agree that we should probably update those docs. :)

**Comment by Dmole** [comment]
Thanks for taking the time to post the link (I already worked around it but nice to know it's fixed upstream)
